name: Docker Image Release

on:
  release:
    types: [created]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v4

    - name: Build image
      run: docker build . --file Dockerfile --tag streamlit-app

    - name: Save Docker Image
      run: docker save streamlit-app -o streamlit-app.tar

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.STREAMLIT_GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: streamlit-app.tar
        asset_name: streamlit-app.tar
        asset_content_type: application/x-tar